### ISSUE TITLE
Running the demo results in ` TypeError: Cannot change graphics instruction outside the main Kivy thread`

### ISSUE THREAD

**Issue by FilipeMarch** [shashi278/svg-anim-kivy#6]
```python
 Exception in thread Thread-1 (show_button_icon):
 Traceback (most recent call last):
   File "/usr/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
     self.run()
   File "/usr/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 982, in run
     self._target(*self._args, **self._kwargs)
   File "/usr/quick-tests/svg-anim-kivy/demo/main.py", line 90, in show_button_icon
     self.draw_filled(s, b.svg_icon)
   File "/usr/quick-tests/svg-anim-kivy/demo/main.py", line 93, in draw_filled
     s.draw(icon)
   File "/usr/quick-tests/svg-anim-kivy/.venv/lib/python3.11/site-packages/kivg/main.py", line 455, in draw
     self.b.canvas.clear()
   File "kivy/graphics/instructions.pyx", line 630, in kivy.graphics.instructions.Canvas.clear
   File "kivy/graphics/instructions.pyx", line 638, in kivy.graphics.instructions.Canvas.clear
   File "kivy/graphics/instructions.pyx", line 674, in kivy.graphics.instructions.Canvas.remove
   File "kivy/graphics/instructions.pyx", line 88, in kivy.graphics.instructions.Instruction.flag_data_update
 TypeError: Cannot change graphics instruction outside the main Kivy thread
```

**Comment by shashi278** [comment]
This has been fixed using mainthread in demo
