### ISSUE TITLE
Bug on DEMO: clicking on stackoverflow/text svg crashes the application

### ISSUE THREAD

**Issue by FilipeMarch** [shashi278/svg-anim-kivy#8]
When you click on `so.svg` or `text.svg` it crashes with the error `AttributeError: 'Kivg' object has no attribute 'closed_shapes'`
![image](https://github.com/shashi278/svg-anim-kivy/assets/23220309/2bc1ac9e-8594-4ff2-ac9d-f048abebffa6)
traceback:
```python
 Traceback (most recent call last):
   File "/usr/quick-tests/svg-anim-kivy/demo/main.py", line 155, in <module>
     KivgDemo().run()
   File "/usr/quick-tests/svg-anim-kivy/.venv/lib/python3.11/site-packages/kivy/app.py", line 956, in run
     runTouchApp()
   File "/usr/quick-tests/svg-anim-kivy/.venv/lib/python3.11/site-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/usr/quick-tests/svg-anim-kivy/.venv/lib/python3.11/site-packages/kivy/base.py", line 339, in mainloop
     self.idle()
   File "/usr/quick-tests/svg-anim-kivy/.venv/lib/python3.11/site-packages/kivy/base.py", line 383, in idle
     self.dispatch_input()
   File "/usr/quick-tests/svg-anim-kivy/.venv/lib/python3.11/site-packages/kivy/base.py", line 334, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/usr/quick-tests/svg-anim-kivy/.venv/lib/python3.11/site-packages/kivy/base.py", line 302, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/usr/quick-tests/svg-anim-kivy/.venv/lib/python3.11/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1191, in kivy._event.EventObservers._dispatch
   File "/usr/quick-tests/svg-anim-kivy/.venv/lib/python3.11/site-packages/kivy/lang/builder.py", line 60, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 65, in <module>
   File "/usr/quick-tests/svg-anim-kivy/demo/main.py", line 146, in shape_animate
     self.s.shape_animate(svg_file, anim_config_list=eval(config), on_complete=self.completed)
   File "/usr/quick-tests/svg-anim-kivy/demo/kivg/main.py", line 93, in shape_animate
     anim_list = self._shape_animate(
                 ^^^^^^^^^^^^^^^^^^^^
   File "/usr/quick-tests/svg-anim-kivy/demo/kivg/main.py", line 132, in _shape_animate
     if self.closed_shapes.get(id_, None):
        ^^^^^^^^^^^^^^^^^^
 AttributeError: 'Kivg' object has no attribute 'closed_shapes'
```

**Comment by shashi278** [comment]
Working for me. Please re-open if you still face this in latest version.
